#!/bin/sh

bundle=$1
if [ "${bundle}" = "" ]; then
	bundle=ORFJDCEROEPFHNMSHLADKENLNHQIPSIFRXPFDHGTNOHWEQPFHHNGBDZLNKXTINFOZBRFNIKEXPRONIUGP
	bundle="UBTJOIAIGPICKDCTVA9DHWTIPEWBUVPPT9QXFHHMNTHLNWRABFRY9LVLMLQYR9OQFXZTV9AKCTLJGQGKU"
	bundle="KLJMSEFGEDMHQUDHHCJLZHUSBMSKM9IDKLGXFESKZQPEQYPRBSPEGEEFEZUCHYPSO9ZZLARHBKCJ9LURL"
fi

curl -s http://localhost:3000/bcfs/retrieve/${bundle} | tail -1 | jq '.data' | sed 's/"//g' | base64 -d
